CREATE TABLE IF NOT EXISTS properties (
  id INT PRIMARY KEY AUTO_INCREMENT,
  color VARCHAR(255) DEFAULT NULL,
  price VARCHAR(255) DEFAULT NULL,
  Size VARCHAR(255) DEFAULT NULL,
  product_id INT NOT NULL,
  CONSTRAINT FK_ProductProperties FOREIGN KEY (product_id) REFERENCES products(id)
  )
