// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name       string         `json:"name"`
	Sku        string         `json:"sku"`
	Properties *NewProperties `json:"properties"`
}

type NewProperties struct {
	Price float64 `json:"price"`
	Color *string `json:"color,omitempty"`
	Size  *string `json:"size,omitempty"`
}
